# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               B02 Biology
tagline:             Fall 2015
name:                B02 Biology
description:         Course materials for B02 Biology
url:                 http://mikheyevlab.github.io/B02-Fall-2015
paginate:            1
baseurl:             /B02-Fall-2015

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  slides:
    output: true

pages_list:
  Schedule: '/schedule'
  Slides: '/slides'
  Syllabus: '/syllabus'
